module.exports = urls = [{
    url: 'https://www.douban.com/group/gz020/?start=',
    // url: 'https://news.ycombinator.com/news?start=',
    label: '广州租房★',
    key: 'gzzf'
  // }
  }, {
    url: 'https://www.douban.com/group/yuexiuzufang/?start=',
    label: '广州越秀租房',
    key: 'gzyxzf'
  }, {
    url: 'https://www.douban.com/group/baiyunzufang/?start=',
    label: '广州白云租房',
    key: 'gzbyzf'
  }, {
    url: 'https://www.douban.com/group/tianhezufang/?start=',
    label: '广州天河租房',
    key: 'gzthzf'
  }, {
    url: 'https://www.douban.com/group/liwanzufang/?start=',
    label: '广州荔湾租房',
    key: 'gzlwzf'
  }, {
    url: 'https://www.douban.com/group/haizhuzufang/?start=',
    label: '广州海珠租房',
    key: 'gzhzzf'
  }, {
    url: 'https://www.douban.com/group/panyuzufang/?start=',
    label: '广州番禺租房',
    key: 'gzpyzf'
  }, {
    url: 'https://www.douban.com/group/gz_rent/?start=',
    label: '广州租房',
    key: 'gzzfgr'
  }, {
    url: 'https://www.douban.com/group/zu.gz.soufun/?start=',
    label: '广州租房交友',
    key: 'gzzfjy'
  }, {
    url: 'https://www.douban.com/group/366393/?start=',
    label: '广州真房实客网租房组',
    key: 'gzzswl'
  }, {
    url: 'https://www.douban.com/group/366393/?start=',
    label: '广州公寓租房信息',
    key: 'gzgy'
  }, {
    url: 'https://www.douban.com/group/216688/?start=',
    label: '广州合租联盟---大学',
    key: 'gzhz'
  }, {
    url: 'https://www.douban.com/group/zunar_gz/?start=',
    label: '广州租房族',
    key: 'gzzfz'
  }, {
    url: 'https://www.douban.com/group/IloveGZ/?start=',
    label: '广州租房（好评度★★★★★）',
    key: 'ilovegz'
  }]